name: multistep_prj
channels:
  - defaults
dependencies:
  - python=3.9
  - pip:
    - mlflow>=1.0
    - boto3==1.23.0
    - numpy==1.21.2
    - matplotlib==3.5.1
    - seaborn==0.11.2
    - pandas==1.3.4
    - scikit-learn==1.0.2
    - click==8.1.2
    - openpyxl==3.0.9
    - fsspec==2022.5.0
    - s3fs==0.4.0
    - pyathena==2.5.0
    - Unidecode==1.3.4
    - pyarrow==8.0.0
    - -e .